Add login
andreicek/productive-cli pull request #2
Opened 2020-08-28 06:26 UTC by kristian240

2020-08-28 09:23 UTC, andreicek requested changes
Thanks! This is amazing work...

Tokens seem to be unstable for some so this should be much better. We should also look into refreshing them but this is enough for now.

2020-08-28 09:23 UTC, andreicek commented on src/config.js
> +  if (!session) {
I would move this if into the createSession, this way we "box" the features and fail in the module.

2020-08-28 09:23 UTC, andreicek commented on src/config.js
> +const { createSession } = require('./session');
If it's not an API I would really like if you could Namespace this import...

```
const Session = require('./session');
```

2020-08-28 09:23 UTC, andreicek commented on src/session.js
> +    console.log('Seems like you have 2FA enabled. Please enter your 2FA code!');
I would drop this log, it should be enough to just prompt the user.

2020-08-28 09:23 UTC, andreicek commented on src/session.js
> +  return session;
Return only the data we need here not the whole JSON API response.

2020-08-28 11:15 UTC, kristian240 commented on src/config.js
> +const { createSession } = require('./session');
So in the code I would call `Session.create`?

2020-08-28 15:25 UTC, kristian240 commented on src/config.js
> +  if (!session) {
How should I handle exception there? I guess instead of returning null, I could throw an error of some kind?

2020-08-29 08:05 UTC, andreicek commented on src/config.js
> +  if (!session) {
Yeah, it's cli we just let it die. We'll worry about correct exit codes sometimes later.

2020-08-29 08:05 UTC, andreicek approved these changes

2020-08-29 08:06 UTC, merged